version: '3.3'

services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
  #   depends_on:
  #     - web
  # # web:
  #   build: ./web
  #   command: gunicorn --bind 0.0.0.0:5000 -w 4 -t 360 wsgi:app

  # training:
  #   image: training:latest


